#!/usr/bin/env bash
set -euo pipefail

version="3.4.1"
app="taskwarrior"
repo="https://github.com/GothenburgBitFactory/taskwarrior"
file="task-${version}.tar.gz"
url="${repo}/releases/download/v${version}/${file}"

XDG_APP_HOME="${XDG_APP_HOME:-$HOME/.local/package}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
XDG_BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"

location="$XDG_APP_HOME/${app}/${version}"
archive="$XDG_APP_HOME/${app}/.archive"

if [ -x "$location/bin/task" ]; then
  echo "[60-taskwarrior] Executable already exists. Skipping build."
else
  mkdir -p "$location" "$archive"

  if [ ! -f "$archive/$file" ]; then
    wget -P "$archive" "$url"
  else
    echo "[60-taskwarrior] Archive already exists, skipping download."
  fi

  build_dir="${location}/build"
  mkdir -p "$build_dir"
  tar -xf "$archive/$file" -C "$build_dir" --strip-components=1

  cd "$build_dir"

  cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$location" .
  cmake --build . --config Release --parallel "$(nproc)" --target install

  rm -rf "$build_dir"
  echo "[60-taskwarrior] Build successful. Cleaned up build directory."
fi

mkdir -p "$XDG_DATA_HOME/zsh/completions" "$XDG_BIN_HOME"
ln -sfn -- "$location/share/zsh/site-functions/_task" "$XDG_DATA_HOME/zsh/completions/_task"
ln -sfn -- "$location/bin/task" "$XDG_BIN_HOME/t"
