#!/bin/bash

# Setup Dotfiles
# alias dots=git --git-dir=$HOME/.dots/ --work-tree=$HOME

echo ".dots" >> .gitignore
git clone --bare https://github.com/arubertoson/dotfiles.git .dots

# Supposed to move files that might be duplicated
mkdir -p .config-backup && \
git --git-dir=.dots/ --work-tree=$HOME checkout 2>&1 \
| egrep "\s+\." \
| awk {'print $1'} \
| xargs -I{} mv {} .config-backup/{}

# Checkout and hide untracked files to avoid unnecessary clutter
git --git-dir=.dots/ --work-tree=. checkout
git --git-dir=.dots/ --work-tree=. config --local status.showUntrackedFiles no

