#!/bin/bash

# Prepare guest addition install
yum -y update
yum install -y gcc kernel-devel kernel-headers dkms make bzip2 perl
export KERN_DIR=/usr/src/kernels/`uname -r`

# Setup mount point
if [[ ! -d /media/vbox ]]; then
  mkdir /media/vbox
fi 
mount -r /dev/cdrom /media/vbox
cd /media/vbox

# Install guest additions
"./VBoxLinuxAdditions.run"

# Cleanup
umount /media/vbox
rmdir /media/vbox

#reboot
