#!/bin/zsh

##
# Main prompt
#

# Auto-remove the right side of each prompt when you press enter. This way,
# we'll have less clutter on screen. This also makes it easier to copy code from
# our terminal.
setopt TRANSIENT_RPROMPT

PROMPT_FRUZ_VICMD_SYMBOL="«"
PROMPT_FRUZ_VIINS_SYMBOL=">"

prompt_fruz_update_prompt() {
  case ${KEYMAP:-main} in
    vicmd)
      PS1="%F{219}${PROMPT_FRUZ_VICMD_SYMBOL}%f "
    ;;
    main|viins|*)
      PS1="%F{%(?,10,9)}${PROMPT_FRUZ_VIINS_SYMBOL}%f "
    ;;
  esac
}

# Keymap widgets are registered after plugins in 08-keys.zsh so prompt and
# cursor updates have one owner and cannot overwrite each other.
prompt_fruz_update_prompt

# Install our chpwd and precmd hook functions.
# https://zsh.sourceforge.io/Doc/Release/Functions.html#Hook-Functions
# -U tells autoload not to expand aliases inside the function.
# -z tells autoload that the function file is written in the default Zsh style.
# The latter is normally not necessary, but better safe than sorry.
autoload -Uz add-zsh-hook
local hook=
for hook in chpwd precmd; do
  add-zsh-hook $hook prompt_fruz_$hook
done
# add-zsh-hook can autoload our functions by name, because in 04-env.zsh, we
# added their parent dir to our $fpath.

##
# Continuation prompt
#
# This prompt is shown if, after pressing enter, you have left unclosed shell
# constructs in your command line, for example, a string without a terminating
# quote or a `for` loop without the final `done`.

PS2=  # Empty the left side, to make it easier to copy code from our terminal.
RPS2="%F{11}%^%f"  # %^ shows which shell constructs are still open.
# 11 is bright yellow.

# If we're not on an SSH connection, then remove the outer margin of the right
# side of the prompt.
[[ -v SSH_CONNECTION ]] ||
    ZLE_RPROMPT_INDENT=0
