[env]
VIRTUAL_ENV_DISABLE_PROMPT = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

[tools]
# Runtimes (fallbacks; projects still pin their own)
node   = "lts"
python = "3.12.9"
go     = "1.25.1"
zig    = "0.15.1"
rust   = "stable"
odin   = "dev-2025-09"
clang  = "21.1.1"
tmux   = "latest"
zellij = "0.43.1"
luajit = "2.1.ROLLING"
jq     = "1.8.1"
process-compose = "1.94"

jujutsu = "latest"
jujutsu-ui = "latest"

# "cargo:https://github.com/Dutch-Raptor/GAT-GWM" = { "version" = "0.4.0" }

yt-dlp = "2025.10.22"
deno = "2"
bun = "latest"

# CLU utils
"github:XAMPPRocky/tokei"	      = "12.1.2"
"github:jdx/usage"		      = "2.2.2"
# "github:oven-sh/bun"             = "bun-v1.2.22"
"github:chmln/sd"		      = "1.0.0"
"github:x-motemen/ghq"	      = "1.8.0"
"github:joshmedeski/sesh"	      = "2.26.2"
"github:alexpasmantier/television"	      = { version = "0.15.7", extract_all = "true" }
"github:cli/cli"		      = { version = "2.89.0", exe = "gh" }
"github:neovim/neovim"	      = { version = "nightly", extract_all= "true", bin_path = "nvim-linux-x86_64/bin" }
"github:astral-sh/uv"            = { version = "0.11.17", extract_all = "true" }
"github:BurntSushi/ripgrep"      = { version = "14.1.1", exe = "rg" }
"github:sharkdp/fd"              = "10.3.0"
"github:eza-community/eza"       = "0.23.4"
"github:sharkdp/bat"             = "0.25.0"
"github:ajeetdsouza/zoxide"      = "0.9.8"
"github:junegunn/fzf"            = "0.65.2"
"github:jesseduffield/lazygit"   = "0.55.1"
"github:casey/just"              = "1.42.0"
"github:watchexec/watchexec"     = "2.3.2"
"github:dandavison/delta"        = "0.18.2"
"github:muesli/duf"              = "0.9.1"
"github:bootandy/dust"           = "1.2.3"
"github:sharkdp/hyperfine"       = "1.19.0"
"github:mikefarah/yq"            = "4.47.2"
"github:aristocratos/btop"       = "1.4.4"
"github:ducaale/xh"              = "0.24.1"
"github:tree-sitter/tree-sitter" = "v0.25.9"
ollama = "latest"

[tasks]

clean = [
	"mise cache clear",
	"mise prune",
]

[settings]
idiomatic_version_file_enable_tools = []
github.use_git_credentials = true
