#! /bin/sh

bspc config border_width 2
bspc config window_gap 0

bspc config top_padding 30
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config normal_border_color "#282c34"
bspc config active_border_color "#282c34"
bspc config focused_border_color "#51afef"
bspc config presel_feedback_color "#181e26"

bspc config ignore_ewmh_focus true

bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config remove_disabled_monitors false

bspc monitor $EXTERNAL_MONITOR -d term code WS.3 WS.4
bspc monitor $PRIMARY_MONITOR -d web WS.2 WS.3 music

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs desktop="^2" state=tiled
bspc rule -a libreoffice desktop="^3" state=floating
bspc rule -a Google-chrome desktop="^5" state=tiled follow=on
bspc rule -a Spotify desktop="^7" state=pseudo_tiled

#bspc rule -a Alacritty state=floating
bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/external_rules"


# TODO: Polybar separate file
if ! pgrep -x "polybar"; then
  polybar_config="$XDG_CONFIG_HOME/polybar/config"
  polybars=(top)
  if [[ ! -z "$EXTERNAL_MONITOR" ]]; then
    polybars+=(external)
  fi

  "${XDG_CONFIG_HOME}"/polybar/launch \
    "${polybar_config}" \
    "${polybars[*]}"
fi

