#! /bin/sh

bspc config border_width 2
bspc config window_gap 2

bspc config top_padding 34
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config normal_border_color "#666666"
bspc config active_border_color "#666666"
bspc config focused_border_color "#cccccc"
bspc config presel_feedback_color "#888888"

bspc config ignore_ewmh_focus true

bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
#bspc config pointer_follows_monitor true
bspc config remove_disabled_monitors false

bspc monitor $EXTERNAL_MONITOR -d term code WS.3 WS.4
bspc monitor $PRIMARY_MONITOR -d web WS.2 WS.3 music

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a emacs desktop='^3' state=floating
bspc rule -a google-chrome desktop='^2' focus=on follow=on
bspc rule -a termite state=floating

# TODO:
# Set Wallpaper with feh
# Start unclutter
# Change cursor to pointer
# Polybar
polybar_config="$XDG_CONFIG_HOME/polybar/config"
polybars=(top)
if [[ ! -z "$EXTERNAL_MONITOR" ]]; then
  polybars+=(external)
fi

"${XDG_CONFIG_HOME}"/polybar/launch \
  "${polybar_config}" \
  "${polybars[*]}"
