#!/usr/bin/env bash


function main() {
  pkill -q polybar &> /dev/null
  
  local config="$1"; 
  local -a bars=("${@}")

  echo "Trying to launch polybar..."
  if ! [[ -e "$config" ]]; then
    echo "No configuration file found"; exit 2
  fi

  for bar in ${bars[*]}; do
    if ! grep -q "\[bar/${bar}\]" "$config"; then
      echo "The bar '${bar}' is not defined in the configuration, skippinng..."; continue
    fi

    polybar "$bar" -c "$config" -r &

    echo "Launched bar '${bar}'"
  done
}

main "$@"

